app/dashboard/student/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, BooleanField, SubmitField
from wtforms.validators import DataRequired, Length, Email, Regexp, EqualTo


class ZapisyForm(FlaskForm):
    reason = StringField('Powód', validators=[DataRequired()])
    submit = SubmitField('Zapisz')  

app/dashboard/teacher/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, BooleanField, SubmitField
from wtforms.validators import DataRequired, Length, Email, Regexp, EqualTo
from wtforms.fields.html5 import DateField, TimeField
from datetime import datetime


class ChangeHoursForm(FlaskForm):
    changeDateField = DateField(
        'Termin', format='%Y-%m-%d', validators=[DataRequired()], default=datetime.now())
    changeTimeField = TimeField(
        'Początek spotkania', format='%H:%M', validators=[DataRequired()])
    changeEndTimeField = TimeField(
        'Koniec spotkania', format='%H:%M', validators=[DataRequired()])
    submit = SubmitField('Zapisz')

app/dashboard/student/__init__.py
from flask import Blueprint

student = Blueprint('student', __name__)

from . import views

app/dashboard/student/views.py
from flask import render_template, redirect, request, url_for, flash, session, jsonify
from flask_login import login_user, logout_user, login_required
from ...models import User, Permission, Entry, Decision
from . import student
from .forms import ZapisyForm
from ... import db
import requests
from flask_wtf import csrf

# noneeded function
# @student.route('/dashboardStudent', methods=['GET', 'POST'])
# def dashboard():
#     login = request.args.get('login')
#     roomId = request.args.get('roomId')
#     loginUrlResult = requests.post(
#         'https://s153070.projektstudencki.pl/API/UsersByLogin.php?login={}'.format(login))
#     roomIdUrlResult = requests.post(
#         'https://s153070.projektstudencki.pl/API/UsersByRoom.php?roomId={}'.format(roomId))
#     try:
#         teacherJson = roomIdUrlResult.json()
#         studentJson = loginUrlResult.json()
#     except:
#         print("roomId or login wrong")

#     # print(teacherJson)
#     if request.method == 'POST':
#         session['teacher_email'] = request.form['email']
#         return redirect(url_for('student.zapisy'))
#     teacher = User.query.filter_by(email=teacherJson['email']).first()
#     student = User.query.filter_by(email=studentJson['email']).first()
#     return render_template('student/dashboard.html', student=student, teacher=teacher)


@student.route('/zapisy', methods=['GET', 'POST'])
def zapisy():
    form = ZapisyForm()
    # print(session['teacher_email'])
    # print(session['student_email'])
    # print(User.query.filter_by(email=session['student_email']).first())
    if 'login' in request.form and 'roomId' in request.form and 'roomAuthtoken' in request.form and 'userAuthtoken' in request.form:
        login = request.form.get('login')
        roomId = request.form.get('roomId')
        roomToken = request.form.get('roomAuthtoken')
        userToken = request.form.get('userAuthtoken')
        # print(login)
        # print(roomId)
        # print(roomToken)
        # print(userToken)
        # roomId = request.args.get('roomId')
        # roomIdUrlResult = requests.post(
        #     'https://s153070.projektstudencki.pl/API/UsersByRoom.php?roomId={}'.format(roomId))
        roomIdUrlResult = requests.post(
            'https://s153070.projektstudencki.pl/API/UsersByRoom.php?roomId={}&token={}'.format(roomId, roomToken))

        loginUrlResult = requests.post(
            'https://s153070.projektstudencki.pl/API/UsersByLogin.php?login={}&token={}'.format(login, userToken))

        try:
            teacherJson = roomIdUrlResult.json()
            studentJson = loginUrlResult.json()
            print(teacherJson)
            print(studentJson)
        except:
            print("roomId or token wrong")

        session['teacher'] = teacherJson
        session['student'] = studentJson
        session['roomId'] = roomId
        session['login'] = login
        # print(User.query.filter_by(email=session['teacher']))
        #session['token'] = token

    # login = request.args.get('login')
    # roomId = request.args.get('roomId')
    # loginUrlResult = requests.post(
    #     'https://s153070.projektstudencki.pl/API/UsersByLogin.php?login={}'.format(login))
    # roomIdUrlResult = requests.post(
    #     'https://s153070.projektstudencki.pl/API/UsersByRoom.php?roomId={}'.format(roomId))
    # try:
    #     teacherJson = roomIdUrlResult.json()
    #     studentJson = loginUrlResult.json()
    # except:
    #     print("roomId or login wrong")

    teacher = User.query.filter_by(email=session['teacher']["email"]).first()
    student = User.query.filter_by(
        email=session['student']["email"]).first()

    if User.query.filter_by(email=session['student']['email']).first() is None:
        user = User(name=session['student']['name'],
                    surname=session['student']['surname'],
                    date="",
                    time="",
                    end_time="",
                    email=session['student']['email'],
                    password='',
                    permission=Permission.STUDENT)
        db.session.add(user)
        db.session.commit()
    else:
        print("student istnieje")

    if User.query.filter_by(email=session['teacher']['email']).first() is None:
        print(session['login'])
        return render_template("student/teacherIsNone.html", student=session['student'])

    if form.validate_on_submit():
        #teacherSession = User.query.filter_by(email=session['teacher_email']).first()
        entry = Entry(student_email=session['student']["email"],
                      teacher_email=session['teacher']["email"],
                      student_name=session['student']["name"],
                      student_surname=session['student']["surname"],
                      teacher_name=session['teacher']["name"],
                      teacher_surname=session['teacher']["surname"],
                      date=teacher.date,
                      time=teacher.time,
                      end_time=teacher.end_time,
                      reason=form.reason.data,
                      decision=Decision.DEFAULT)
        db.session.add(entry)
        db.session.commit()
        return redirect(url_for('student.results'))
    return render_template('student/zapisy.html', form=form, login=session['login'], teacherSession=session['teacher'], teacher=teacher, studentSession=session['student'])


@student.route('/resultsStudent', methods=['GET', 'POST'])
def results():
    if 'login' in request.form and 'userAuthtoken' in request.form:
        login = request.form.get('login')
        userToken = request.form.get('userAuthtoken')
        # roomId = request.form.get('roomId')
        loginUrlResult = requests.post(
            'https://s153070.projektstudencki.pl/API/UsersByLogin.php?login={}&token={}'.format(login, userToken))
        # roomIdUrlResult = requests.post(
        #     'http://localhost/API/UsersByRoom.php?login={}&token={}'.format(roomId, roomToken))
        try:
            # teacherJson = roomIdUrlResult.json()
            studentJson = loginUrlResult.json()
        except:
            print("roomId or login wrong")

        # session['teacher'] = teacherJson
        session['student'] = studentJson
        # session['roomId'] = roomId
        session['login'] = login
    entries = Entry.query.filter_by(
        student_email=session['student']["email"])
    # print(login)
    return render_template('student/results.html', entries=entries, student=session['student'])

app/dashboard/teacher/__init__.py
from flask import Blueprint

teacher = Blueprint('teacher', __name__)

from . import views

app/dashboard/teacher/views.py
from flask import render_template, redirect, request, url_for, flash, session
from flask_login import login_user, logout_user, login_required
from ...models import User, Permission, Entry, Decision
from ... import db
from . import teacher
from ...user.forms import TeacherRegistrationForm
import requests
from .forms import ChangeHoursForm
import datetime


@teacher.route('/dashboardTeacher', methods=['GET', 'POST'])
def dashboard():
    form = TeacherRegistrationForm()
    if 'roomId' in request.form and 'roomAuthtoken' in request.form:
        roomId = request.form.get('roomId')
        token = request.form.get('roomAuthtoken')
        print(roomId)
        print(token)
        # roomId = request.args.get('roomId')
        # roomIdUrlResult = requests.post(
        #     'https://s153070.projektstudencki.pl/API/UsersByRoom.php?roomId={}'.format(roomId))
        roomIdUrlResult = requests.post(
            'https://s153070.projektstudencki.pl/API/UsersByRoom.php?roomId={}&token={}'.format(roomId, token))

        try:
            teacherJson = roomIdUrlResult.json()
            print(teacherJson)
        except:
            print("roomId or token wrong")

        session['teacher'] = teacherJson
        session['roomId'] = roomId
        session['token'] = token

    # teacher = User.query.filter_by(email=teacherJson['email']).first()

    if request.method == 'POST':
        if request.form.get("submit"):
            user = User(name=session['teacher']['name'],
                        surname=session['teacher']['surname'],
                        date=str(form.date.data),
                        time=str(form.time.data),
                        end_time=str(form.end_time.data),
                        email=session['teacher']['email'],
                        password='',
                        permission=Permission.TEACHER)
            db.session.add(user)
            db.session.commit()
        if request.form.get("accept"):
            id = request.form['accept']
            entry = Entry.query.filter_by(id=id).first()
            entry.decision = Decision.ACCEPT
            db.session.commit()
        if request.form.get("decline"):
            id = request.form['decline']
            entry = Entry.query.filter_by(id=id).first()
            entry.decision = Decision.DECLINE
            db.session.commit()

    #  prowadzacy1 = User.query.filter_by(email='student1@wp.pl').first() -> prowadzacy1.date
    if User.query.filter_by(email=session['teacher']['email']).first() is None:
        return render_template('user/register.html', form=form)
    else:
        print("prowadzacy istnieje")

    entries = Entry.query.filter_by(teacher_email=session['teacher']['email'])
    # user = User.query.filter_by(email=session['teacher_email']).first()
    # prowadzacy1 = User.query.filter_by(email='testMail@test.pl').first()
    # print(prowadzacy1.date)
    for entry in entries:
        today = datetime.datetime.today()
        todayOnlyDay = today.strftime('%d')
        date_time_str = entry.date
        date_time_obj = datetime.datetime.strptime(date_time_str, '%Y-%m-%d')
        entryTime = date_time_obj.strftime('%d')
        expectedDate = int(todayOnlyDay) - int(entryTime)
        print(expectedDate)
        if expectedDate > 7:
            db.session.delete(entry)
            db.session.commit()
    return render_template('teacher/dashboard.html', entries=entries, roomId=session['roomId'],
                           teacher=session['teacher'], roomAuthtoken=session['token'])


# po changeEntryHours podac wartosc roomId
@teacher.route('/changeEntryHours', methods=['GET', 'POST'])
def changeEntryHours():
    form = ChangeHoursForm()
    # roomId = request.form.get('roomId')
    # token = request.form.get('roomAuthtoken')
    # roomIdUrlResult = requests.post(
    #     'http://localhost/API/UsersByRoom.php?roomId={}&token={}'.format(roomId, token))
    # try:
    #     teacherJson = roomIdUrlResult.json()
    # except:
    #     print("login wrong")
    print(session['teacher'])

    if form.validate_on_submit():
        teacher = User.query.filter_by(
            email=session['teacher']["email"]).first()
        teacher.date = str(form.changeDateField.data)
        teacher.time = str(form.changeTimeField.data)
        teacher.end_time = str(form.changeEndTimeField.data)
        # user = User(date=str(form.changeDateField.data),
        # time=str(form.changeTimeField.data),
        # end_time=str(form.changeEndTimeField.data))

        # print(str(form.changeDateField.data))
        # print(str(form.changeTimeField.data))
        # print(str(form.changeEndTimeField.data))
        db.session.commit()
        # po zmienie dyzuru idą args w params
        return redirect(url_for('teacher.dashboard'))
    return render_template('teacher/changeEntryHours.html', form=form, roomId=session['roomId'])

app/templates/student/dashboard.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %} Login {% endblock %}

{% block navbar %}
<!-- Navigation -->
    <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
        <a class="navbar-brand"><img src="static/logo.png"></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('student.dashboard') }}">Zapisy</a>
                </li>
                <li class="nav-item">
                    {% if current_user.is_authenticated %}
                    <a class="nav-link" href="{{ url_for('user.logout') }}">Wyloguj się</a>
                    {% else %}
                    <a class="nav-link" href="{{ url_for('user.login') }}">Zaloguj się</a>
                    {% endif %} 
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{{ url_for('student.results') }}">Odpowiedzi</a>
              </li>
                <li class="nav-item">
                    <a class="nav-link" href="#features">Informacje</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#clients">Klienci</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#contact">Kontakt</a>
                </li>
            </ul>
        </div>
    </nav><!-- End Navigation -->
{% endblock navbar%}

{% block name_form %}
  <div class="captionForms text-center">
    
    <h1>Czesc {{ student.name }}</h1>
    <h3>Lista Prowadzacych do ktorych mozesz sie zapisac</h3>
    
        
    <!-- <div class="center_div  ">
      <form method = "post">
        {% for user in users %}
        <p>{{ user.username }}</p>
        <button type="submit" value="{{ user.email }}" name="email">Example</button>
        {% endfor %}
    </div> -->
    <table class="table table-bordered">
      <thead>
        <tr>
          <th scope="col">Imie</th>
          <th scope="col">Nazwisko</th>
          <th scope="col">Email</th>
          <th scope="col">Data</th>
          <th scope="col">Zapisz sie</th>
        </tr>
      </thead>
      <h3>{{teacher.name}}</h3>
      <tbody>
        <tr>
          <td>{{ teacher.name }}</td>
          <td>{{ teacher.surname }}</td>
          <td>{{ teacher.email }}</td>
          <td>{{ teacher.date }} {{ teacher.time }}-{{ teacher.end_time}}</td>

        </tr>
      </tbody>
    </table>
  </div>
{% endblock %}


<!-- <td><form method = "post"> 
  <button type="submit" class="btn btn-outline-light btn-lg" value="{{ user.email }}" name="email">Zapisz</button>
</form></td> -->

app/templates/student/results.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %} Login {% endblock %}

{% block navbar %}
<!-- Navigation -->
    <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
        <a class="navbar-brand"><img src="static/logo.png"></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="#features">Informacje</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#clients">Klienci</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#contact">Kontakt</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="javascript:window.open('','_self').close();">Wróc do Wykłady Webowe</a>
                    <!-- href="javascript:window.open('','_self').close();" -->
                </li>
            </ul>
        </div>
    </nav><!-- End Navigation -->
{% endblock navbar%}

{% block name_form %}
    <div class="captionForms text-center">
        <h1>Witaj {{ student.name }}</h1>
        <h3>Dyżury, na które się zapisałeś</h3>

        <table class="table table-bordered">
            <thead>
              <tr>
                <th scope="col">Imię</th>
                <th scope="col">Nazwisko</th>
                <th scope="col">Email</th>
                <th scope="col">Data</th>
                <th scope="col">Powód</th>
                <th scope="col">Decyzja</th>
              </tr>
            </thead>
            <tbody>
              {% for entry in entries %}
              <tr>
                <td>{{ entry.teacher_name }}</td>
                <td>{{ entry.teacher_surname }}</td>
                <td>{{ entry.teacher_email }}</td>
                <td>{{ entry.date }} {{ entry.time }}-{{ entry.end_time }}</td>
                <td>{{ entry.reason }}</td>
                <td>
                  {% if entry.decision == 1 %}
                    <a>Zaakceptowano</a>
                {% elif entry.decision == 2 %}
                    <a>Odmowa</a>
                {% else %}
                    <a>Oczekujące</a>
                {% endif %}
                </td>
              </tr>
              </tbody>
              {% endfor %}
        </table>
    </div>
{% endblock %}

app/templates/student/teacherIsNone.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %} Login {% endblock %}

{% block navbar %}
<!-- Navigation -->
    <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
        <a class="navbar-brand"><img src="static/logo.png"></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="#features">Informacje</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#clients">Klienci</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#contact">Kontakt</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('student.results')}}">Twoje Konsultacje</a>
                <li class="nav-item">
            </ul>
        </div>
    </nav><!-- End Navigation -->
{% endblock navbar%}

{% block name_form %}
  <div class="captionForms text-center">
    
    <h1>Czesc {{ student.name }}</h1>
    <h3>Poproś prowadzącego o wprowadzenie godzin dyżuru</h3>
        <a href="javascript:window.open('','_self').close();">
            <button type="submit" class="btn btn-outline-light btn-lg">Wróc do Wykłady Webowe</button>
        </a>
    
  </div>
{% endblock %}

app/templates/student/zapisy.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %} Zapisy {% endblock %}

{% block navbar %}
<!-- Navigation -->
    <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
        <a class="navbar-brand"><img src="static/logo.png"></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('student.results')}}">Twoje Konsultacje</a>
                <li class="nav-item">
                    <a class="nav-link" href="#features">Informacje</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#clients">Klienci</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#contact">Kontakt</a>
                </li>
            </ul>
        </div>
    </nav><!-- End Navigation -->
{% endblock navbar%}

{% block name_form %}
<div class="captionForms text-center">
        <h1>Wypełnij formularz {{ studentSession.name }}</h1>
        <h3>Dzień oraz godzina spotkania </h3>
        <h4>Prowadzącego {{ teacherSession.name }} {{ teacherSession.surname }} </h4>
        <h4>{{teacher.date}}   {{ teacher.time }}</h4>
    <div class="center_div ">
        {{ wtf.quick_form(form) }}
        {{ form.csrf_token }}
    </div>
</div>
{% endblock %}